apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  tasks:
    - name: npminstall
      taskRef:
        name: npm

    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine

    - name: build
      runAfter:
        - tests
      taskRef:
        name: npm
